
# Site settings
title: CartLab
description: Your global hub for smart cart and modern property solutions
author: CartLab Team
email: partners@cartlab.web.id
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cartlab.web.id" # the base hostname & protocol for your site
logo: /assets/img/cartlab-logo.svg
default_image: /assets/img/default-post-image.svg
copyright_year: © 2025
keywords:
  - smart cart
  - property technology
  - cart automation
  - smart property
  - real estate
  - smart living
  - IoT
  - cartlab

# Build settings
markdown: kramdown
permalink: /:title/
incremental: true
include: ["_pages"]
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude system files and folders from processing and watching
exclude:
  - .local
  - .replit
  - .cache
  - .config
  - .git
  - .jekyll-cache
  - .bundle
  - vendor
  - Gemfile
  - Gemfile.lock
  - replit.nix
  - node_modules
  - "*.tmp"
  - "*.bak"
  - .sass-cache
  - .DS_Store

# Prevent regeneration of site for specific files
keep_files:
  - .git
  - .jekyll-metadata

# Plugins with optimized settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-paginate

# Enhanced minifier settings
jekyll-minifier:
  exclude: ['*.xml', '*.json', '*.txt', '*.png', '*.jpg', '*.jpeg', '*.webp', '*.svg']
  compress_css: true
  compress_javascript: true
  compress_html: true
  html_minifier_options:
    remove_comments: true
    remove_empty_attributes: true
    collapse_whitespace: true
    minify_css: true
    minify_js: true
    
# Pagination settings
paginate: 12
paginate_path: "/page/:num/"

# SEO settings
twitter:
  username: cartlab
  card: summary_large_image
facebook:
  app_id: 
  publisher: 
  admins: 
social:
  name: CartLab
  links:
    - https://twitter.com/cartlab
    - https://facebook.com/cartlab
    - https://instagram.com/cartlab
    - https://linkedin.com/company/cartlab

# Analytics
google_analytics: 

# Disqus comments
disqus:
  shortname: cartlab

# AdSense optimization
adsense:
  client_id: ca-pub-2501282943430263
  enable_page_level_ads: true
  enable_in_article_ads: true
  enable_sidebar_ads: true
  enable_popup_ads: false
  popup_timeout: 5
  posts_per_home: 12
  ad_slots:
    header: 9766157847
    sidebar: 9766157847
    in_article: 9766157847
    footer: 9766157847
  article_ad_positions:
    - 300
    - 600
    - 900

# Default configurations
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      toc: true
      share: true
      related: true
      slug: "post-default-slug"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      slug: "page-default-slug"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
      slug: "category-default-slug"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
      slug: "tag-default-slug"
  - scope:
      path: ""
    values:
      slug: "default-post"

# Content settings
show_excerpts: true
excerpt_separator: <!--more-->

# Image optimization
generate_images_from_title: true
prefer_webp: true
responsive_image_sizes: [300, 600, 900]

# Widget optimization
widgets:
  sidebar:
    enabled: true
    recent_posts: true
    categories: true
    tags: false
    popular_posts: true
    advertisement: true
  footer:
    enabled: true
    about: true
    categories: true
    recent_posts: true
    tags: false
  post:
    share_buttons: true
    
# Featured posts
featured_posts:
  enabled: true
  count: 6
  show_excerpt: true
  excerpt_length: 150
  title: "Featured Articles"
  display_author: true
  display_date: true
  display_categories: true

# Performance optimization
compress_html: true
compress_css: true
compress_js: true
use_async_scripts: true
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Jekyll processing optimization
future: false
unpublished: false
safe: false
disable_disk_cache: false
profile: false
